# Generated by Django 5.2.10 on 2026-02-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0006_remove_inventoryitem_client_and_more'),
        ('TogaMeasurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womenmeasurement',
            name='client',
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=10)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='TogaClients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MenMeasurement',
        ),
        migrations.DeleteModel(
            name='WomenMeasurement',
        ),
    ]
