# Generated by Django 5.2.10 on 2026-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaMeasurements', '0003_menmeasurement_womenmeasurement_delete_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menmeasurement',
            old_name='tom_cuff',
            new_name='cuff',
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='tom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
