# Generated by Django 5.2.10 on 2026-06-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaMeasurements', '0004_rename_tom_cuff_menmeasurement_cuff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menmeasurement',
            name='tailors_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Recorded By'),
        ),
        migrations.AlterField(
            model_name='womenmeasurement',
            name='tailors_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Recorded By'),
        ),
    ]
