# Generated by Django 5.2.10 on 2026-06-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaMeasurements', '0005_alter_menmeasurement_tailors_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menmeasurement',
            name='tailors_name',
        ),
        migrations.RemoveField(
            model_name='womenmeasurement',
            name='tailors_name',
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='System User'),
        ),
        migrations.AddField(
            model_name='menmeasurement',
            name='tailor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tailor Name'),
        ),
        migrations.AddField(
            model_name='womenmeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='System User'),
        ),
        migrations.AddField(
            model_name='womenmeasurement',
            name='tailor_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tailor Name'),
        ),
    ]
