# Generated by Django 5.2.10 on 2026-02-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0004_client_updated_at'),
        ('TogaInventory', '0002_material_reorder_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid Fully', 'Paid Fully'), ('Partially', 'Partially')], default='Partially', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='TogaClients.client')),
            ],
        ),
    ]
