# Generated by Django 5.2.10 on 2026-02-11 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaInventory', '0003_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
