# Generated by Django 5.2.10 on 2026-02-28 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaInventory', '0004_alter_inventory_date_of_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='inventory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cleared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='paid_fully',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='paid_fully_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
