# Generated by Django 5.2.10 on 2026-03-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0007_remove_client_email'),
        ('TogaInventory', '0005_delete_material_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='inventory',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact number for this inventory record', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='client',
            field=models.ForeignKey(help_text='The client this inventory record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='TogaClients.client'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(help_text='Details of the material selected or brought'),
        ),
    ]
