# Generated by Django 5.2.10 on 2026-04-15 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0007_remove_client_email'),
        ('TogaInventory', '0006_remove_inventory_phone_number_inventory_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The worker who created this inventory record', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['client'], name='TogaInvento_client__9bdb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['paid_fully'], name='TogaInvento_paid_fu_1f01f7_idx'),
        ),
    ]
