# Generated by Django 5.2.10 on 2026-05-01 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaInventory', '0007_inventory_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Charged'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='amount_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Deposited'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cleared_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cleared By'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Collection Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The worker who created this inventory record', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deposit Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(help_text='Details of the material selected or brought', verbose_name='Material Description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='paid_fully',
            field=models.BooleanField(default=False, verbose_name='Paid Fully?'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='paid_fully_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Fully Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact number for this inventory record', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Received By'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('received_by', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='TogaInventory.inventory')),
            ],
        ),
    ]
