# Generated by Django 5.2.10 on 2026-01-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0003_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
