# Generated by Django 5.2.10 on 2026-02-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0006_remove_inventoryitem_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
