# Generated by Django 5.2.10 on 2026-06-09 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TogaClients', '0007_remove_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='client_phone_lookup_idx',
            old_name='TogaClients_phone_b6b80f_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='client_name_lookup_idx',
            old_name='TogaClients_name_e29e1e_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid normalized identity phone digits sequence format.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
